In [7]:
import pandas as pd

In [9]:
df = pd.read_csv('diabetes.csv')

In [10]:
df.head(17)

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72.0,35,169.5,33.6,0.627,50,1
1,1,85,66.0,29,102.5,26.6,0.351,31,0
2,8,183,64.0,32,169.5,23.3,0.672,32,1
3,1,89,66.0,23,94.0,28.1,0.167,21,0
4,0,137,40.0,35,168.0,43.1,2.288,33,1
5,5,116,74.0,27,102.5,25.6,0.201,30,0
6,3,78,50.0,32,88.0,31.0,0.248,26,1
7,10,115,70.0,27,102.5,35.3,0.134,29,0
8,2,197,70.0,45,543.0,30.5,0.158,53,1
9,8,125,96.0,32,169.5,34.3,0.232,54,1
10,4,110,92.0,27,102.5,37.6,0.191,30,0
11,10,168,74.0,32,169.5,38.0,0.537,34,1
12,10,139,80.0,27,102.5,27.1,1.441,57,0
13,1,189,60.0,23,846.0,30.1,0.398,59,1
14,5,166,72.0,19,175.0,25.8,0.587,51,1
15,7,100,74.5,32,169.5,30.0,0.484,32,1
16,0,118,84.0,47,230.0,45.8,0.551,31,1

In [11]:
df.shape

(768, 9)

In [12]:
df.columns

Index(['Pregnancies', 'Glucose', 'BloodPressure', 'SkinThickness', 'Insulin',
       'BMI', 'DiabetesPedigreeFunction', 'Age', 'Outcome'],
      dtype='object')

In [13]:
df.dtypes

Pregnancies                   int64
Glucose                       int64
BloodPressure               float64
SkinThickness                 int64
Insulin                     float64
BMI                         float64
DiabetesPedigreeFunction    float64
Age                           int64
Outcome                       int64
dtype: object

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 768 entries, 0 to 767
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Pregnancies               768 non-null    int64
 1   Glucose                   768 non-null    int64
 2   BloodPressure             768 non-null    float64
 3   SkinThickness             768 non-null    int64
 4   Insulin                   768 non-null    float64
 5   BMI                       768 non-null    float64
 6   DiabetesPedigreeFunction  768 non-null    float64
 7   Age                       768 non-null    int64
 8   Outcome                   768 non-null    int64
dtypes: float64(4), int64(5)
memory usage: 54.1 KB

In [15]:
df.describe()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
count,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000
mean,3.845052,121.677083,72.389323,29.089844,141.753906,32.434635,0.471876,33.240885,0.348958
std,3.369578,30.464161,12.106039,8.890820,89.100847,6.880498,0.331329,11.760232,0.476951
min,0.000000,44.000000,24.000000,7.000000,14.000000,18.200000,0.078000,21.000000,0.000000
25%,1.000000,99.750000,64.000000,25.000000,102.500000,27.500000,0.243750,24.000000,0.000000
50%,3.000000,117.000000,72.000000,28.000000,102.500000,32.050000,0.372500,29.000000,0.000000
75%,6.000000,140.250000,80.000000,32.000000,169.500000,36.600000,0.626250,41.000000,1.000000
max,17.000000,199.000000,122.000000,99.000000,846.000000,67.100000,2.420000,81.000000,1.000000

CHECK DATA QUALITY

In [17]:
df.isnull().sum()

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64

In [18]:
df.duplicated().sum()

np.int64(0)

In [20]:
df['Age'].unique()

array([50, 31, 32, 21, 33, 30, 26, 29, 53, 54, 34, 57, 59, 51, 27, 41, 43,
       22, 38, 60, 28, 45, 35, 46, 56, 37, 48, 40, 25, 24, 58, 42, 44, 39,
       36, 23, 61, 69, 62, 55, 65, 47, 52, 66, 49, 63, 67, 72, 81, 64, 70,
       68])

**SELECTING AND FILTERING**

In [21]:
df['Glucose']

0      148
1       85
2      183
3       89
4      137
      ...
763    101
764    122
765    121
766    126
767     93
Name: Glucose, Length: 768, dtype: int64

In [22]:
df[['Glucose','BMI','Age']]

     Glucose   BMI  Age
0        148  33.6   50
1         85  26.6   31
2        183  23.3   32
3         89  28.1   21
4        137  43.1   33
..       ...   ...  ...
763      101  32.9   63
764      122  36.8   27
765      121  26.2   30
766      126  30.1   47
767       93  30.4   23

[768 rows x 3 columns]

FILTERING ROWS BY CONDITIONS--

In [23]:
df[df.Age>50]

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
8,2,197,70.0,45,543.0,30.5,0.158,53,1
9,8,125,96.0,32,169.5,34.3,0.232,54,1
12,10,139,80.0,27,102.5,27.1,1.441,57,0
13,1,189,60.0,23,846.0,30.1,0.398,59,1
14,5,166,72.0,19,175.0,25.8,0.587,51,1
...,...,...,...,...,...,...,...,...,...
719,5,97,76.0,27,169.5,35.6,0.378,52,1
734,2,105,75.0,27,102.5,23.3,0.560,53,0
757,0,123,72.0,32,169.5,36.3,0.258,52,1
759,6,190,92.0,32,169.5,35.5,0.278,66,1
763,10,101,76.0,48,180.0,32.9,0.171,63,0

In [24]:
df[(df['Age']>50)&(df[df['Outcome']]==1)]

KeyError: "None of [Index([1, 0, 1, 0, 1, 0, 1, 0, 1, 1,\n       ...\n       0, 1, 0, 1, 0, 0, 0, 0, 1, 0],\n      dtype='int64', length=768)] are in the [columns]"

# CHECK INVALID VALUE--

In [25]:
(df[['Glucose','BloodPressure','SkinThickness']])

     Glucose  BloodPressure  SkinThickness
0        148           72.0             35
1         85           66.0             29
2        183           64.0             32
3         89           66.0             23
4        137           40.0             35
..       ...            ...            ...
763      101           76.0             48
764      122           70.0             27
765      121           72.0             23
766      126           60.0             32
767       93           70.0             31

[768 rows x 3 columns]

In [26]:
df.isin([0]).sum()

Pregnancies                 111
Glucose                       0
BloodPressure                 0
SkinThickness                 0
Insulin                       0
BMI                           0
DiabetesPedigreeFunction      0
Age                           0
Outcome                     500
dtype: int64

ACCESS ROWS BY INDEX

In [27]:
df.iloc[0:17]

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72.0,35,169.5,33.6,0.627,50,1
1,1,85,66.0,29,102.5,26.6,0.351,31,0
2,8,183,64.0,32,169.5,23.3,0.672,32,1
3,1,89,66.0,23,94.0,28.1,0.167,21,0
4,0,137,40.0,35,168.0,43.1,2.288,33,1
5,5,116,74.0,27,102.5,25.6,0.201,30,0
6,3,78,50.0,32,88.0,31.0,0.248,26,1
7,10,115,70.0,27,102.5,35.3,0.134,29,0
8,2,197,70.0,45,543.0,30.5,0.158,53,1
9,8,125,96.0,32,169.5,34.3,0.232,54,1
10,4,110,92.0,27,102.5,37.6,0.191,30,0
11,10,168,74.0,32,169.5,38.0,0.537,34,1
12,10,139,80.0,27,102.5,27.1,1.441,57,0
13,1,189,60.0,23,846.0,30.1,0.398,59,1
14,5,166,72.0,19,175.0,25.8,0.587,51,1
15,7,100,74.5,32,169.5,30.0,0.484,32,1
16,0,118,84.0,47,230.0,45.8,0.551,31,1

SHORTING AND GROUPING ---